name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Enable Corepack
      run: corepack enable

    - name: Use the Correct Yarn Version
      run: corepack prepare yarn@4.6.0 --activate

    - name: Install dependencies
      run: yarn install

    - name: Set Environment Variables for GitHub Pages
      run: echo "VITE_BASE_URL=/fortune-telling-website/" >> $GITHUB_ENV

    - name: Build project
      run: yarn build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
